### ISSUE TITLE
Manuelles Feld: Erfasste Mitglieder

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#101]
**Ausgangslage:**
Aktuell gibt es auf der Gruppe (nur bei Vereinen) ein berechnetes Feld "Erfasste Mitglieder". Einige Organisationen (SJM) erfassen ihre Mitglieder nicht in hitobito. 

**Ziel:**
Der SJM sollte das Feld «Erfasste Mitglieder» manuell befüllen können. Man müsste also einer Gruppe die Berechtigung geben können (von mir aus auch händisch direkt in der DB, weil es nur die SJM betrifft), dass ihre Untergruppen statt der einzelnen Mitgliedern direkt das Total erfassen können.

# Tech-Spec

- [x] DB-Feld für `groups.reported_members` (int) hinzufügen
- [x] DB-Feld für `groups.manually_counted_members` (boolean) hinzufügen
- [x] Wenn `manually_counted_members` auf `true` gesetzt ist:
    - [x] das berechnete Feld ausblenden und `reported_members` anzeigen
    - [x] in `Group#edit` die Anzahl der Mitglieder bearbeitbar machen
    - [x] im Export "CSV-Untergruppen" auch `reported_members` statt dem berechneten Feld ausgeben
    - [x] besser reported_members getter anpassen anstatt CSV export. dies stellt sicher das das Feld auch an anderen Orten richtig angezeigt wird
- [x] Rake-Tasks, die das Feature pro Gruppe aktivieren oder deaktivieren. 
    - [x] Beim Aktivieren das Flag auch bei allen Untergruppen setzen
    - [x] Beim Aktivieren die Zahl auf 0 setzen

**Comment by olibrian** [comment]
In der Info Seite einer Gruppe sollte das Feld `Mitglieder manuell erfasst` nur bei den Gruppen angezeigt werden, wo auch die manuelle Erfassung möglich ist. Sonst irritiert dies etwas.

**Comment by carlobeltrame** [comment]
Habs auf der Integrationsumgebung in dieser Gruppe aktiviert: https://sbv.puzzle.ch/de/groups/1309

**Comment by olibrian** [comment]
Können wir das Label noch anpassen: "Anzahl Mitglieder (manuell)"
![image](https://user-images.githubusercontent.com/9592347/144396453-1cba9bda-41b9-41f2-8f07-f90bddc2293a.png)

**Comment by betsim** [comment]
Welche Rolle muss ich haben, damit das Feld für mich editierbar ist?
Und wenn das neue Feld angezeigt wird, würde ich das berechnete Feld ausblenden. Und das neue in "Erfasste Mitglieder (manuell)" benennen, der Einheitlichkeit halber.

**Comment by olibrian** [comment]
Ich fasse kurz zusammen:

- [ ] In der Info Seite einer Gruppe sollte das Feld Mitglieder manuell erfasst nur bei den Gruppen angezeigt werden, wo auch die manuelle Erfassung möglich ist. 
- [ ] Label auf Edit und View anpassen: "Erfasste Mitglieder (manuell)" 
- [ ] Beim Testen in der Gruppe https://sbv.puzzle.ch/de/groups/1309 wurde der eingegebene Wert nicht gespeichert. Grüne Bestätigung wird angezeigt aber Wert wird nicht gespeichert.

**Comment by olibrian** [comment]
Gemäss Kunde kann in der Version 1.26.45 bei den Jugendmusiken keinen einzigen Verein finden, bei dem man die Anzahl Mitglieder manuell erfassen könnte (Beispiel: https://db.windband.ch/de/groups/7009).

**Comment by carlobeltrame** [comment]
Ja, klar. Ich habe nur deployed, ohne spezielle weitere Aktionen zu unternehmen. Dieses Feature müssen wir manuell auf jeder einzelnen solchen speziellen Gruppe aktivieren. Dafür brauche ich eine abschliessende Liste mit allen Gruppen, wo das aktiviert werden soll.

**Comment by betsim** [comment]
Olivier meinte zwar, er wisse, welche Gruppen das Feature bekommen, aber gerne hier noch für alle:

- [ ] alle Vereine vom Schweizer Jugendmusikverband (https://db.windband.ch/de/groups/164/)
- [ ] alle Vereine, die den Schweizer Jugendmusikverband als "weitere Gruppenzugehörigkeit" aufweisen

Reicht dir diese Regel @carlobeltrame oder möchtest du eine Namensliste?

**Comment by carlobeltrame** [comment]
Merci, diese Information war nicht bis zu mir durchgedrungen. Ich habe die manuell erfassten Mitglieder jetzt auf insgesamt 90 Vereinen aktiviert.

**Comment by betsim** [comment]
Wir haben einen Usecase ausser Acht gelassen: 

- [ ] Wenn Personen erfasst sind und keine manuelle Anzahl eingetragen ist (spricht das Feld leer oder 0 ist), sollte natürlich weiterhin das berechnete Feld angezeigt werden.

Beispiel: https://db.windband.ch/de/groups/7504
