### ISSUE TITLE
FEATURES: Aktivieren von Core Features für SBV Wagon

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#104]
Für die Umgebung SBV folgende Features aktivieren:

- [x] Adressvervollständigung auf Personen (Token + manueller Import)
- [x] Tägliche Validierung der Adressen einer Person (läuft bereits, aber hat noch keine Adressen. Job so ändern dass er nur läuft wenn das Adress-Verzeichnis da ist)
- [x] Warteliste für Events (`:waiting_list` zu den `used_attributes` von `Event` hinzufügen)
- [x] Spam Mailbox (Rollen mit Admin-Permissions sollten dies bereits können, Generalverband-Admin, Dachverband-Admin)
- [x] Rechnungsbriefe/Briefe (im Wagon-settings.yml: `messages.enable_writing: true`, `assignments.enabled: true`)
- [ ] ~Gruppen archivieren #1275 -> was sind die Bedingungen dazu?~ zur Zeit noch nicht aktivieren

**Comment by kronn** [comment]
- Adressvervollständigung und -validierung benötigt nur das Token, um die Daten zu holen und einen manuellen Import
- Die Warteliste wird aktiviert, wenn für Events `waiting_list` in den `used_attributes` ist
- Gruppen können archiviert werden, wenn sie keine Untergruppen mehr enthalten.

**Comment by carlobeltrame** [comment]
Beim Gruppen archivieren gibts wohl im Zusammenhang mit Musikfesten so einiges zu testen, bevor das dann wirklich sattelfest läuft.

**Comment by betsim** [comment]
> Beim Gruppen archivieren gibts wohl im Zusammenhang mit Musikfesten so einiges zu testen, bevor das dann wirklich sattelfest läuft.

Dann schlage ich vor, dieses Feature vorerst aussen vor zu lassen, damit die Aktivierung der restlichen Funktionen nicht verzögert wird.

**Comment by betsim** [comment]
Wie steht es mit diesem Ticket?

**Comment by TheWalkingLeek** [comment]
Addressen sind importiert und Addressvervollständigung kann getestet werden
https://sbv.puzzle.ch
