### ISSUE TITLE
SUISA: Aufführung im vergangen Jahr hinzufügen 

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#111]
## Aktuelles Verhalten

Wenn im Jahr 2022 eine Meldung aus dem Jahr 2021 getätigt wird, kommt diese ins SUISA Jahr 2022, auch wenn Datum im 2021 ist:

![image](https://user-images.githubusercontent.com/9592347/148571215-0380e4ba-9d80-4478-8ea3-fe65ba5dcb3b.png)

Beispiel:
Fanfare Union Buix ist im 2021 nicht spielfähig: https://db.windband.ch/de/groups/11694/concerts?year=2021

In der Übersicht von Société district de Porrentruy hat Buix nicht eingereicht: https://db.windband.ch/de/groups/16956/song_censuses?year=2021

## Gewünschtes Verhalten

Bei der Eingabe ob ein Verein Spielfähig ist oder nicht, soll diese noch im vergangen Jahr möglich sein.

## Schritte zum reproduzieren

1. Meldeliste ist noch offen
2. Eintrag erfassen im Jahr 2021
3. Speichern
4. Aufführung wird im 2022 angezeigt
5. Entsprechend kann die Meldeliste für 2021 nicht eingereicht werden

# Tech-Spec

- ...

# ToDo

**Comment by kronn** [comment]
Ich kann den Fehler leider nicht nachvollziehen. Im aktuellen Datenbestand wurde die Meldeperiode am 2022-01-02 abgeschlossen. Wenn ich versuche das lokal nachzustellen, wird die Meldung richtig zugeordnet. Ich schließe das Issue erstmal, es kann aber auch gerne wieder eröffnet werden, wenn weitere Informationen vorhanden sind.

**Comment by betsim** [comment]
> Ich kann den Fehler leider nicht nachvollziehen. Im aktuellen Datenbestand wurde die Meldeperiode am 2022-01-02 abgeschlossen. Wenn ich versuche das lokal nachzustellen, wird die Meldung richtig zugeordnet. Ich schließe das Issue erstmal, es kann aber auch gerne wieder eröffnet werden, wenn weitere Informationen vorhanden sind.

Falls auf der **Produktiv**-Umgebung die Meldeperiode am 2. Januar 2022 geschlossen wurde, wäre dies unabsichtlich passiert und müsste rückgängig gemacht werden (können wir irgendwo sehen, ob eine Periode abgeschlossen wurde?). Wir müssen noch Meldungen für 2021 erfassen können.

**Comment by kronn** [comment]
Es scheint in der Tat so zu sein. Die aktuelle Meldeperiode heißt "2022" und geht vom 2022-01-02 bis (erstmal 2022-21-31). Abgeschlossen wird eine Meldeperiode, wenn eine neue angelegt wird. Ich gehe davon aus, dass der "Abschluss" am Berchtoldstag gemacht wurde, weil dieses Datum an allen revelanten Stellen auftaucht.

Das erklärt aber auch das Verhalten, dass es nicht im gewünschten/erwarteten Jahr erscheint. hitobito nimmt an, dass die aktuelle Periode 2022 ist. Alle aktuellen Meldungen werden seit dem 2022-01-02 der Meldeperiode 2022 zugeordnet.

Sollen aktuell _alle_ Meldungen der Meldeperiode 2021 zugeordnet werden? Also sowohl "nicht spielfähig"-Meldungen wie auch Aufführungen, die direkt eingetragen werden?

Die Meldeperioden sind so gemacht, dass immer nur eine aktiv sein kann. Ich könnte aber alle neuen Meldungen/Aufführungen von 2022 direkt in der Datenbank auf 2021 ändern. Weiterhin könnte ich ggf. noch die Meldeperiode 2021 wieder aktivieren, indem ich die Meldeperiode 2022 lösche. Dies würde ich auch manuell in der DB machen.

**Comment by betsim** [comment]
Ja, bitte "öffnet" die Periode 2021 nochmals, damit wir noch Einträge machen können und bitte ändert die Einträge 2022 auf 2021.

In einem zweiten Schritt müssten wir (ihr) abklären, welche Rollen die Berechtigung haben, eine Meldeperiode zu schliessen; wir können nämlich nicht nachvollziehen, wer das gemacht hat.

Herzlichen Dank für Eure Unterstützung!

**Comment by kronn** [comment]
Ich habe die Meldeperiode wieder eröffnet und die 2022er gelöscht. Die Einträge, die bereits der neuen Periode zugeordnet waren, sind der 2021er Meldeperiode zugeordnet.

**Comment by kronn** [comment]
Soweit ich es sehe, haben die Rollen

- Administrator
- Verantwortlicher SUISA

die Berechtigung, die Meldeperiode abzuschliessen und eine neue zu starten. Der Button "Meldeliste abschliessen" gibt dabei eine Warnmeldung aus, die bestätigt werden muss:

> Mit dem Abschliessen der Meldeliste werden alle bis jetzt eingereichten Meldungen gesperrt. Es wird eine neue Meldeliste angelegt, noch offene Meldungen werden dann allenfalls dieser Liste hinzugefügt.

Braucht es eine Möglichkeit für euch, das rückgängig zu machen? Da keine direkte Meldung an die SUISA gemacht wird, wäre es inhaltlich möglich. Es fixiert ja nur den Datenbestand und versehentliche Änderungen zu vermeiden.

Oder braucht es eine Nachvollziehbarkeit, wer die neue Meldeperiode angelegt hat? Hier könnte man den jeweiligen Benutzer hinterlegen. Positiv ausgedrückt könnte man das nutzen, um das auf dem Benutzer anzuzeigen und es im Jahresbericht dankend zu erwähnen. Im Falle eines Versehens könnte man natürlich auch gezielte Aufklärungsarbeit unter vier Augen leisten.

**Comment by betsim** [comment]
Leider haben wir die Meldeperiode versehentlich schon wieder abgeschlossen. Grund war, dass Hanspeter Frischknecht für einen Verein deren SUISA-Liste einreichen wollte – dabei wurde nicht nur die Liste des Vereins eingereicht, sondern gleichzeitig auch die ganze Meldeperiode abgeschlossen.  Hier scheint es ein konzeptionelles Problem zu geben, wenn Personen verschiedene (SUISA-)Rechte besitzen. Werde dazu ein separates Ticket eröffnen.

**Wäre super, wenn ihr die Meldeperiode nochmals öffnen könntet.** Es ist keine zusätzliche Rückdatierung erforderlich.
