### ISSUE TITLE
MESSAGES: mail relay undefined method mail_domain

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sbv#114]
https://github.com/hitobito/hitobito_sbv/blob/7381b70692a40ed85049f5257773a8ec1b1e0758/app/domain/sbv/mail_relay/lists.rb#L16

falls beim Empfangen einer E-Mail keine Mailingliste assigned werden kann, wird eine Exception geworfen.

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47151/?query=is%3Aunresolved%20mail_domain

mail ignorieren falls keine Mailinglist assigned werden kann.

**Comment by TheWalkingLeek** [comment]
Das Issue ist aus unserer Sicht mit Nutzung des neuen Mail Stacks behoben. Daher schliessen wir es erstmal, sollten doch noch Probleme auftreten kann es wieder geöffnet werden.
