### ISSUE TITLE
ANLÄSSE: Anhänge in der API verfügbar machen

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#120]
Wir wollen die in hitobito hinterlegten Anlässe zukünftig auch auf unserer Website darstellen. Dafür benötigen wir ein zusätzliches Feld für eine Bild-URL. Über die Funktion "Anhänge" lässt sich das leider nicht lösen, weil diese nicht in der API mitgegeben werden. 

In der API gibt es aber ein Feld "motto", welches aber in unserem Waggon (richtigerweise) nicht angezeigt wird. Am schnellsten wäre es wohl, wenn dieses Feld wieder eingeblendet werden würde und wir das für die Bild-URL missbrauchen würden. Auf dem Info-Tab des Anlasses sollte das Feld dann nicht angezeigt werden (könnte man m.E. sehr einfach über CSS steuern).

In einem zweiten Schritt könnte man dafür natürlich ein eigenständiges und korrekt benanntes Feld einführen, welches auch in der API erscheint. Oder man überlegt sich, ob die URL der Anhänge in der API erscheinen sollen.

**Comment by carlobeltrame** [comment]
Ich würde eher ein eigenes Feld dafür einführen, welches wirklich für diesen Zweck gedacht ist. Das führt sonst nur zu Verwirrung (intern heisst das Feld halt weiterhin `motto`) und zu Mehraufwand wenn wir später die bereits eingegebenen Bild-URLs vom Motto-Feld ins richtige Feld migrieren müssen. Ein neues Feld hinzuzufügen oder die Anhänge über die API verfügbar zu machen ist beides kein besonders grosser Aufwand.

Sind die Bilder immer extern gehostet und ihr wollt tatsächlich nur eine URL darin speichern? Oder braucht ihr die Möglichkeit für einen Datei-Upload?

**Comment by betsim** [comment]
Wir suchen nach einer möglichst schnell umsetzbaren Variante, weshalb ich auf das bestehende Feld gekommen bin. Alternativ gäbe es noch das bestehende Feld "Anhänge", welches sogar einen Dateiupload bietet. Dieses ist aber nicht in der API vorhanden. Die Bilder müssen m.E. nicht zwingend in hitobito gehostet werden und können problemlos extern bleiben. Aber wenn wir das über die Anhänge lösen können inkl. Hosting, dann ist das natürlich perfekt.

**Comment by carlobeltrame** [comment]
Die Anhänge in der API auszugeben ist ungefähr gleich wenig Aufwand wie das Motto-Feld via Übersetzungen umzubenennen und es in der API und im Formular wieder einzublenden, nicht aber in der Detailansicht (sogar wenn wir vom späteren zusätzlichen Migrationsaufwand absehen).
Es müsste nur hier eingefügt werden: https://github.com/hitobito/hitobito/blob/master/app/serializers/event_serializer.rb#L77
Und ein trivialer AttachmentSerializer dafür von einem der bestehenden Serializers kopiert und angepasst werden: https://github.com/hitobito/hitobito/tree/master/app/serializers

Es geht wirklich nicht schneller wenn wir das Motto-Feld dafür missbrauchen.

**Comment by betsim** [comment]
Ok, umso besser! Ich bin sehr damit einverstanden, wenn das über Anhänge gelöst werden kann 👍

**Comment by mtnstar** [comment]
issue für umsetzung erstellt: https://github.com/hitobito/hitobito/issues/1873
