### ISSUE TITLE
Übersetzung: DirigentIn

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#121]
Die korrekte italienische Übersetzung von "DirigentIn" (Rolle auf Stufe Verein) lautet offenbar: 

> direttore/direttrice

![Bildschirm­foto 2022-11-01 um 16 25 22](https://user-images.githubusercontent.com/1453303/199271151-f6caf7be-f5ba-4ee9-ab2b-ed8f42406cc4.png)
Aktuell ist der String mit "Direttrice" übersetzt.

Ich kann diesen String in Transifex aber nicht finden. Kann @olibrian oder @kronn mir weiterhelfen?

**Comment by olibrian** [comment]
Im Transifex müssen sowohl Einzahl wie Mehrzahl übersetzt werden:
![2022-11-18_11-20](https://user-images.githubusercontent.com/9592347/202711037-521c07f9-6b73-419d-844a-899a4612c042.png)

**Comment by betsim** [comment]
Danke für die Aufklärung!
