### ISSUE TITLE
INVOICE: Nacharbeiten Mitgliederbeitrag

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_sbv#131]
### Aktuelles Verhalten

1: Beim Rechnung erstellen auf einer Person kann "Normale Rechnung" und "Mitgliederbeitrag" gewählt werden.

2: Zahlungsinformationen, welche in den Einstellungen als Default definiert sind, werden im Rechnungsformular nicht vorausgefüllt.

3: Der Name der Rechnungsposten "Mitgliederbeitrag" ist nicht bearbeitbar. 

4: Beim Versuch einen Mitgliederbeitrag ohne Titel zu speichern, erhält man einen 500er.

### Gewünschtes Verhalten

1: Beim Rechnung erstellen auf einer Person kann ausschliesslich "Normale Rechnung" gewählt werden.

2: Zahlungsinformationen, welche in den Einstellungen als Default definiert sind, werden im Rechnungsformular vorausgefüllt.

3: Der Name der Rechnungsposten "Mitgliederbeitrag" ist bearbeitbar. 

4: Wie bei den normalen Rechnungen sollte die Meldung erscheinen, dass der Titel der Rechnung fehlt.

### Schritte zu reproduzieren

1: Auf der Person > +Rechnung erstellen

2: Bei Rechnugseinstellungen Defaults definieren > Rechnungen für Mitgliederbeitrag erstellen

3: Rechnungen für Mitgliederbeitrag erstellen

4: Mitgliederbeitrag erstellen > Titel leerlassen > speichern

### Wann ist der Fehler aufgetreten?

06.2023

### Organisation

SBV

### Screenshots, weiterer Kontext

1: 
![image](https://github.com/hitobito/hitobito/assets/69250571/d372e847-b771-4a91-a4de-2c0cd8989497)

## ToDo

- [x] 1
- [x] 2
- [x] 3
- [x] 4

**Comment by TheWalkingLeek** [comment]
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/63293/?query=is%3Aunresolved%20is%3Aunassigned
