### ISSUE TITLE
Spalte Aktivjahre fehlt auf Integrationsumgebung

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#133]
Auf der Integrationsumgebung fehlt die - auf der Produktivumgebung existierende - Spalte "Aktivjahre": https://sbv.puzzle.ch/de/groups/1592/people?returning=true

**Bitte umgehend beheben, bevor das versehentlich live geht.**

![image](https://github.com/hitobito/hitobito_sbv/assets/1453303/cd228b89-db5c-414f-89d2-2da9a75de793)

**Comment by carlobeltrame** [comment]
Merci für die Meldung, ich habe das gleich behoben. Müsste morgen auf der Integrationsumgebung verfügbar sein.
