### ISSUE TITLE
SUISA Liste ink. Aufführung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#21]
Analog der bestehende SUISA soll ein zusätzlicher Export möglich sein, welcher noch die Aufführung enthält. 

Der Export unter SUISA-Zusammenfassung (song_counts) entspricht der aktuellen SUISA Liste. Soll so beibehalten werden.
Der Export unter SUISA-Aufführungen (concerts) enthält alle Aufführung mit den Werken. Dabei sollen gleiche Werke nicht zusammengefasst werden.

- [ ] Anpassung Dropdown
- [ ] Zusätzlicher Export concerts

**Comment by olibrian** [comment]
Issue wird aktuell noch zurückgestellt. Wird von den Chören verwendet und Finanzierung ist noch unklar.

**Comment by betsim** [comment]
Ticket kann geschlossen werden.
