### ISSUE TITLE
Neues SUISA Jahr eröffnen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#22]
Neue Funktion: Jahr eröffnen. Jeweils per Stichtag wird das vergangen Jahr abgeschlossen und ein neues SUISA-Jahr eröffnet. Erst ab diesem Zeitpunkt können neue Aufführungen erfasst werden.  Im vergangen Jahr können keine Mutationen mehr durchgeführt werden.

Offene Fragen an den SBV:
-    Wer darf ein neues Jahr eröffnen?
-    Ist das Datum der Durchführung relevant? Oder der Zeitpunkt des Eintrages?

**Comment by olibrian** [comment]
Aktuell keine Priorität seitens SBV

**Comment by betsim** [comment]
Ticket kann geschlossen werden.
