### ISSUE TITLE
Berechtigung im Verlauf

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#25]
Ein normaler User (kein Admin) kann in seinem Verlauf eine weitere Rolle hinzufügen. Danach erscheint eine Fehlermeldung aber die Rolle wird trotzdem hinzugefügt. Nachvollziehbar auf der Integrationsumgebung mit dem User https://sbv.puzzle.ch/de/groups/16/people/12006/history)

Gewünschtes Verhalten:
Nur der Administrator darf den Verlauf einer Person anpassen. Ein User ohne entsprechende Rechte soll den Button nicht sehen.

Original Issue: https://github.com/hitobito/hitobito/issues/602

**Comment by olibrian** [comment]
Aus dem Austausch mit dem SBV vom 6.2.2020:
Die Rolle "Administrator" ist wie folgt zu verstehen:

Gewünschte Berechtigung:
Folgende User dürfen den Verlauf hinzufügen:
* Admin
* Admin Verband
* Admin Kantonalerverband
* Admin Regionalerverband
* Admin Verein
Person selber darf keine Verläufe hinzufügen 

Löschen von Einträgen auf dem Benutzer:
* Admin
* Admin Verband
* Admin Kantonalerverband

**Comment by olibrian** [comment]
Ergänzende Anpassungen:
* Verlauf darf nur durch schreibberechte Person erfasst werden (aktuell bereits so gelöst)
* Im Verlauf darf eine beliebige Organisation angegeben werden.
* Beim Erfassen von einem Verlauf soll das Feld "Bis" Pflicht sein. Entsprechende Kennzeichnung und Check bei der Eingabe. Dieses Feld muss ein Datum aus der Vergangenheit sein.

**Comment by kronn** [comment]
Ich schliesse das hier jetzt. Wenn noch Anpassungen nötig sind, kann man das hier wieder eröffnen oder ein neues Ticket erstellen (jenachdem, was dann sinnvoller erscheint).
