### ISSUE TITLE
BUV und NBUV Lohnsumme in hitobito

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#30]
**Felder**
- [x] Zusätzliches Feld BUV-Lohnsumme auf dem Verein. Typ Zahl.
- [x] Zusätzliches Feld NBUV-Lohnsumme auf dem Verein. Typ Zahl.

**Export**

- [x] CSV Export von Unfallversicherung Lohnsumme mit folgenden Spalten:
- Verein
- BUV-Lohnsumme
- NBUV-Lohnsumme

**Berechtigung**

- [x] Generalverband - Administrator -> CSV Export, Eingabe auf allen Organisationen
- [x] Dachverband - Administrator -> CSV Export, Eingabe auf allen Organisationen
- [x] Mitgliederverband - Administrator ->  CSV Export, Eingabe auf allen Organisationen
- [x] Regionalverband - Administrator -> Keine Berechtigung, Feld nicht sichtbar
- [x] Verein - Administrator -> Eingabe auf seinem Verein
- [x] Alle anderen -> Keine Berechtigung, Feld nicht sichtbar

**Comment by kronn** [comment]
Man könnte die `:finance`-Berechtigung verwenden, man müsste dann nur den Eingabesonderfall für den Vereinsadministrator erstellen. `:layer_and_below_full` haben alle Admins, daher eignet sich `:finance` deutlich besser. Passt auch aus meiner Sicht besser.
