### ISSUE TITLE
Einmaliger grosser Export

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#35]
Der SBV möchte gerne ein Export von allen Mitgliedern. Ich habe mir dies mal in der Integration (https://sbv.puzzle.ch/de/groups/1/mailing_lists/28/) zusammengeklickt. Leider dauert der Export ewig. Haben wir eine Alternative einen grossen Export zu machen? 
Folgende Attribute sind notwendig: 

- Name
- Vorname
- Name des Primären Vereines
- Mailadresse des Mitgliedes
- Korrespondenzsprache

**Comment by kronn** [comment]
@olibrian ich habe dir die Daten direkt geschickt und schliesse das Ticket hier. Wenn es nicht passt, bitte wieder eröffnen mit den Hinweis, was noch fehlt.

**Comment by olibrian** [comment]
Danke. Ich denke dies passt so.

**Comment by olibrian** [comment]
Rückmeldung, es brauch noch ein Feld `Korrespondenzsprache`
