### ISSUE TITLE
EMF: Generalisierung Musikfeste

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#40]
Das Konstrukt von einem Anlass wo sich Gruppen anmelden, soll generalisiert werden. Dies zum Zweck, dass neben dem EMF auch weitere (Musik)Feste davon profitieren können.
* Wenn ein kantonaler Event erstellt wird, soll dies auch durch den Administrator dies können. Allgemein Layer-and-below sollte auch nach Anmeldeschluss noch bearbeiten können.
* Wo können die Kategorien definiert werden? 
* Wo können die Spieltage definiert werden? 
* Konfigurierbar pro Event über ein GUI?
* Wie können wir dies lösen? → Wer darf was? → Vorschlag von Puzzle erarbeiten

Offene Fragen:
* Sind die Kategorien fix definiert?
* Welche Daten sind variabel welche nicht? 

-> Nachfrage bei Reto/Bernhard

**Comment by betsim** [comment]
Nach meinem aktuellen Kenntnisstand ist dieses Thema nicht mehr aktuell --> für's erste: wontfix
