### ISSUE TITLE
EMF: 2. Phase für die Anmeldung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#41]
Weitere Informationen welche noch gemeldet werden (nach dem Anmeldeschluss)
Neuanmeldung soll nicht mehr möglich sein

Bestehende Felder sind «readonly»

Ab einem 2. Anmeldetermin ab 1. Oktober 2020 zusätzliche Angaben:

- Selbstwahl Stückangaben
        ◦ Wer liefert diese Liste? Frage an Bernhard
            ▪ Suisa Liste aufarbeiten mit Klassen
            ▪ Wettstückliste verwenden (https://www.windband.ch/de/wettstuecke/wettstueckliste/)
            ▪ Achtung: Parademusik nur CH-Komponisten
            ▪ Achtung: Ohne Import, aktualisieren, Datenbereinigung etc
            ▪ Achtung: Wie funktioniert es bei anderen Musikfeste
        ◦ Regel welche Stücke dürfen ausgewählt werden (Annahme Werkstückliste vorhanden) → 2PT
            ▪ Es dürfen nur Stücke der Gewählte Klasse und um eine höhere Klasse ausgewählt werden
            ▪ Ein Stück pro Anmeldung
            ▪ Ein Stück falls Parademusik ausgewählt ist
            ▪ Ein Kommentarfeld falls Unterhaltungsmusik anstelle Auswahl
            ▪ Ein Kommentarfeld falls Parademusik mit Show anstelle Auswahl
- Spielplan (Upload)

**Comment by betsim** [comment]
Ticket kann geschlossen werden. Weitere Daten werden in der separat zu entwickelnden Software für Musiktage erfasst.
