### ISSUE TITLE
EMF: Definitives Mitgliederverzeichnis

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#42]
~~13. März 2021 → Button, welcher das definitive Mitgliederverzeichnis erstellt.~~

~~Alle Mitglieder welche zu diesem Zeitpunkt im Verein sind Teilnehmer sind.~~

~~Möglichkeit:~~
~~* Mitglieder in eine eigene Gruppe ~~
~~* Mitglieder als Teilnehmer auf dem Event~~
~~* Liste exportieren mit Mitgliedern der Vereine~~
~~Berechtigung beim Administrator vom Layer wo der Anlass ist oder darüber.~~

~~Fragen:~~
~~* Wie ist der Umgang mit nachträglichen Anmeldungen und Abmeldungen (Reto)~~
~~* Braucht es den "Dirigent"? Von wo kommt diese Information? Ist dies die Rolle "DirigentIn"?~~

Einmaliger Export, Details definieren. Per 13. März 2021

**Comment by betsim** [comment]
Ticket kann geschlossen werden. Weitere Daten werden in der separat zu entwickelnden Software für Musiktage erfasst.
