### ISSUE TITLE
EMF: Info-Tab funktioniert direkt nach Anmeldung zu Musikfest nicht

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sbv#45]
Vorbereitung: Ein Musikfest (id z.B. 361) auf SBV (id z.B. 2) erstellen und den Admin eines beliebigen Vereins (id z.B. 241) impersonieren
1. Zum Verein des impersonierten Admins wechseln
    * URL: `/groups/241`
2. Auf das Tab "Musikfeste" wechseln
    * URL: `/groups/241/our_festival_participations`
3. Auf den Button "Anmelden" klicken
    * URL tatsächlich: `/groups/241/events/361/group_participations/new?participating_group=241`
    * URL erwartet: `/groups/2/events/361/group_participations/new?participating_group=241`
4. Anmeldung als Spielgemeinschaft -> nein und Button "Speichern" klicken
    * URL tatsächlich: `/groups/241/events/361/group_participations/9/edit?participating_group=241`
    * URL erwartet: `/groups/2/events/361/group_participations/9/edit`
5. Auf Tab "Info" klicken
    * URL tatsächlich: `/groups/241/events/361`
    * URL erwartet: `/groups/2/events/361`
    * Fehlermeldung: ActiveRecord::RecordNotFound; Couldn't find Event with 'id'=361 [WHERE `events_groups`.`group_id` = ?]

Wenn man wegnavigiert und später zur GroupParticipation zurückkommt, ist die URL jeweils korrekt. Das Problem tritt momentan nur direkt nach der Gruppenanmeldung auf.

**Comment by betsim** [comment]
Ticket kann geschlossen werden. Weitere Daten werden in der separat zu entwickelnden Software für Musiktage erfasst.
