### ISSUE TITLE
Hinweisetexte SUISA Erinnerung pro Kanton definierbar

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#50]
Ist: Aktuell ist der Hinweistext "Meldeliste: E-Mail Erinnerung " https://sbv.puzzle.ch/de/custom_contents/15/edit global definiert. Der Hinweistext wird hier verwendet: https://sbv.puzzle.ch/de/groups/1/song_censuses/2/remind

Soll: Der Hinweistext soll pro Kanton unterschiedlich definierbar sein. Berechtigung soll analog zum "Erinnerung versenden" sein

**Comment by betsim** [comment]
Ticket kann geschlossen werden bitte.
