### ISSUE TITLE
Anpassungen Berechtigungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#53]
Anpassungen an den Berechtigungen
- [x] Berechtigung contact_data auf allen Rollen entfernen
- [x] Berechtigung des kantonalen «Suisa Verantwortlichen» ergänzen, damit diese Rolle auch auf den Vereinen die SUISA Rechte hat.
- [x] Gelöschte Gruppen nur für Personen mit Schreibrechte sichtbar
https://sbv.puzzle.ch/de/groups/1/deleted_subgroups

**Comment by betsim** [comment]
@kronn Können die erledigten Punkte bereits unter https://sbv.puzzle.ch getestet werden?

**Comment by kronn** [comment]
Leider nein. ich setze alle Punkte in eine Feature-Branch um, welcher noch nicht auf dre Integration sichtbar ist.

**Comment by kronn** [comment]
Diese Feature (oder diese Sammlung von Features) sollte jetzt auf der Integration sichtbar sein, da es nächtlich aktualisiert wird. Geschlossene Tickets sind damit eigentlich immer am nächsten Tag verfügbar.

**Comment by betsim** [comment]
Person mit der Rolle "Verantwortlicher SUISA" (Stufe Kantonalverband [Beispiel: Christina Brunner im Aargauischen Musikverband]) kann bei einem Verein weder Aufführungen hinzufügen, noch eine alternative Erledigungsart wählen. Fehler: Sie sind nicht berechtigt, diese Seite anzuzeigen.

**Comment by kronn** [comment]
Bei neu angelegten Aufführungen wird die Verbindung zum Mitgliederverband erst beim Speichern gesucht und gesetzt. Die Zugangsberechtigung wird jedoch schon vorher geprüft. Zu diesem Zeitpunkt war die neue Aufführung (nach eigener Meinung) keine Mitgliederverband zugeordnet, daher konnte die Berechtigungen nicht geprüft werden. Jetzt ist dies so angepasst, dass die Berechtigungsprüfung nochmal genauer bei der Aufführung nachfragt und dann auch - sofern alles stimmt - das Speichern erlaubt.

Zum Hintergrund: die alternative Erledigungsart legt auch "nur" eine Aufführung an, bei der jedoch eine entsprechende Begründung hinterlegt ist. Damit ist die Berechtigungsprüfung für eine neue echte Aufführung und eine "Platzhalter"-Aufführung genau gleich.

Ich habe diese Änderung auch noch auf der Integration ausgerollt, damit dort alles getestet werden kann.
