### ISSUE TITLE
SUISA: GUI-Fehler in Navigation

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#60]
IST: Zeigt man im Menü SUISA "Aufführungen" an, ist korrekterweise das list-item "SUISA" mit class='active' ausgezeichnet (und erhält einen roten Strich). Wechselt man zu "Zusammenfassung" wird das list-item "Info" als 'active' ausgezeichnet [1]

ERWARTET: Egal welche Ansicht gewählt ist, im Menü SUISA soll immer dieses list-item mit  class='active' ausgezeichnet sein [2]

![Bildschirmfoto 2020-07-10 um 21 55 54](https://user-images.githubusercontent.com/1453303/87197497-b1462c00-c2fa-11ea-8a02-6f13a26cdfc4.png)

**Comment by olibrian** [comment]
Danke @betsim für die Info. Wir gehen dies im nächsten Sprint an.
