### ISSUE TITLE
EMF 3. Phase

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#62]
Zusätzliche Angaben:
    • Primäre Anreise Art (Bahn, Schiff, Personenwagen (Anzahl), Car) → Auswahlfeld nur eines auswählbar. Kommentarfeld (Bei PW, bitte Anzahl angeben)
    • Möchtet der Verein ein Foto vor Ort? [ja / nein] Details werden noch geliefert
    • Begleitpersonen Anzahl (Zahlenfeld)
    • Catering (als Kommentarfeld)

**Comment by betsim** [comment]
Ticket kann geschlossen werden. Weitere Daten werden in der separat zu entwickelnden Software für Musiktage erfasst.
