### ISSUE TITLE
Mail via Abos

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#64]
Gemäss Aussage von Kunde funktionieren die Mailabos noch nicht. MX sollte korrekt sein. Habe heute 22.7.2020 um 14:39 ein Testmail mit dem Betreff "mailtest 1439" an mailtest@db.windband.ch geschickt. Auf dem Verteilier ist hitobito@puzzle.ch. Bis jetzt ist noch kein Mail angekommen.

**Comment by KunoKunz** [comment]
Ich habe das gleiche Problem immer noch bei den Multitenants. @kronn hat da bereits einmal etwas gemacht, aber wie gesagt besteht das Problem immer noch.

**Comment by kronn** [comment]
Es scheint mit diesen Fehlern (zumindest zeitlich) zusammenzuhängen: 

- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/17581
- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/9388

Ich nehme die Mail erstmal aus der INBOX und speichere sie im Folder `failing` zur weiteren Analyse.

**Comment by psunix** [comment]
die methode envelope_sender wird im wagon überschrieben:

https://github.com/hitobito/hitobito_sbv/blob/master/app/domain/sbv/mail_relay/lists.rb#L10

hier wird super gecalled mit 3 argumenten. #envelope_sender hat aber keine argumente in base und auch lists vom vore.

@carlobeltrame weisst du was die Idee hier ist?

**Comment by carlobeltrame** [comment]
Ich habe nur einen Typo gefixt der im Sentry aufgetaucht ist. Die Methode wurde bereits vor einem Jahr überschrieben, im Rahmen von hitobito/hitobito#787. Vielleicht weiss @amaierhofer mehr?

**Comment by psunix** [comment]
@olibrian mailingliste sollte nun gefixt sein.
muss natürlich erst noch released werden damits dann mit den abos funzt :wink:
