### ISSUE TITLE
Korrespondenzsprache Rätoromanisch

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#70]
Ergänzen der Korrespondenzsprache mit "Rätoromanisch"

- Hat diese Ergänzung noch weitere Konsequenzen? Mailversand?

**Comment by kronn** [comment]
Die Korrespondenzsprache ist an die verfügbaren Sprachen (also: Übersetzungen) vom Wagon gekoppelt. Daher müsste man alles übersetzen, inklusive der CustomContents, welche dann auch für den Mailversand verwendet werden. Man könnte versuchen, hier eine Abkürzung zu nehmen, ich vermute aber, dass das fast aufwendiger ist, als eine weitere Übersetzung zu ermöglichen. Den Aufwand für die Übersetzung selbst kann ich leider nicht abschätzen.

**Comment by betsim** [comment]
Aus Sicht SBV könnten die rätoromanischen Texte einfach auch auf deutsch sein. Es geht uns einzig um die Kennzeichnung der Korrespondenzsprache.
