### ISSUE TITLE
Berechnung Aktivjahre

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#73]
**SOLL**
Für die Berechnung der Aktivjahre ist nur die Rolle MITGLIED in der Gruppe MITGLIEDER massgebend. Alle anderen Gruppen/Rollen generieren keine Aktivjahre. Beim Löschen oder Editieren einer Rolle soll die Berechnung der Aktivjahre sofort ausgeführt werden.

**IST**
Beim Löschen einer Rolle wird keine neue Berechnung der Aktivjahre durchgeführt. Die Berechnung der Aktivjahre für die Rollen in der Gruppe MITGLIEDER folgt zudem aktuell keiner erkennbaren Regel, wie nachfolgende Beispiele zeigen:

```
⚠️ Passivmitglied seit 01.09.2015 = 6 Aktivjahre
= falsch: diese Rolle generiert keine Aktivjahre

⚠️ Adressverwaltung seit 01.09.2015 = 6 Aktivjahre
= falsch: diese Rolle generiert keine Aktivjahre

⚠️ Ehrenmitglied seit 01.09.2015 = 6 Aktivjahre
= falsch: diese Rolle generiert keine Aktivjahre

✅ Mitglied seit 01.09.2015 = 6 Aktivjahre
= richtig: diese Rolle generiert Aktivjahre

✅ Mitglied sei 01.09.2015
+ Passivmitglied seit 01.09.2010
+ Adressverwaltung seit 01.09.2009
+ Ehrenmitglied sei 01.09.2008 = 6 Aktivjahre
= richtig: nur die Rolle MITGLIED generiert Aktivjahre

⚠️ Passivmitglied seit 01.09.2010
+ Adressverwaltung seit 01.09.2009
+ Ehrenmitglied seit 01.09.2008 = 13 Aktivjahre
= falsch: diese Rollen generieren keine Aktivjahre; gezählt werden jedoch die Jahre von Ehrenmitglied

⚠️ Adressverwaltung seit 01.09.2009
+ Ehrenmitglied seit 01.09.2008  = 13 Aktivjahre
= falsch: diese Rollen generieren keine Aktivjahre; gezählt werden die Jahre von Ehrenmitglied

⚠️ Adressverwaltung seit 01.09.2009
+ Passivmitglied seit 01.09.2010 = 11 Aktivjahre
= falsch: diese Rollen generieren keine Aktivjahre; gezählt werden die Jahre von Passivmitglied (hier kommt hinzu: keine Ahnung, wieso in dieser Konstellation nicht die Rolle Adressverwaltung mit 12 Jahren gezählt wird)
 
⚠️ Passivmitglied seit 01.09.2010
+ Adressverwaltung seit 01.09.2009 = 11 Aktivjahre
= falsch: diese Rollen generieren keine Aktivjahre; gezählt werden die Jahre von Passivmitglied (hier kommt hinzu: keine Ahnung, wieso in dieser Konstellation nicht die Rolle Adressverwaltung mit 12 Jahren gezählt wird; Beispiel wie vorheriges, aber mit umgekehrter Reihenfolge beim Erfassen der Rollen, was aber offenbar keinen Einfluss hat)

```

**Comment by kronn** [comment]
Neu werden nur noch die "Mitglieder"-Rollen in den Mitgliedergruppen der Vereine gezählt, siehe https://github.com/hitobito/hitobito_sbv/commit/6c24a2b9643d87fff741dc5ebc1121992c11cba5

Die anderen Rollen in der Gruppe Mitglieder werden nicht mehr berücksichtigt. Die Neu-Berechnung passiert immer, wenn eine Mitgliederrolle gespeichert oder gelöscht wird und einmal jährlich für alle Personen.

**Comment by betsim** [comment]
Sieht gut aus, vielen Dank! 👍🏻

@kronn bitte daran denken: man muss beim going live über alle Personen hinweg die Aktualisierung manuell anstossen – aktuell stimmen die Zahlen auf der Integrationsumgebung erst dann, wenn neue Rollen hinzugefügt werden.

**Comment by kronn** [comment]
@betsim Ganz vergessen, das hier auch noch zu schreiben: Die Anpassungen wurden ausgerollt und die Aktivjahre einmal für alle Personen neu berechnet.
