### ISSUE TITLE
SUISA-Modul: fehlende/leere Übersetzung

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#76]
Die drei Strings: `Spielgemeinschaft, nicht spielfähig in diesem Jahr, SUISA über Dritte abgerechnet` im SUISA-Modul sind in den Sprachen französisch und italienisch leer. Wenn keine Übersetzung vorliegt, muss die deutsche Version angezeigt werden.

<img width="470" alt="Bildschirmfoto 2020-10-07 um 09 36 48" src="https://user-images.githubusercontent.com/1453303/95301438-e6720400-0880-11eb-90f8-2f1d546e173a.png">

**Comment by olibrian** [comment]
In der Tat sind noch einige Strings nicht übersetzt. Aktuell sind folgende Strings nicht auf Französisch und Italienisch übersetzt. 


DE | FR | IT
-- | -- | --
aktive Mitgliedschaft |   |  
sekundäre Zugehörigkeit |   |  
weitere Zugehörigkeit |   |  
E-Mailadresse Kontaktperson |   |  
gespielt |   |  
Spielgemeinschaft |   |  
nicht spielfähig in diesem Jahr |   |  
SUISA über Dritte abgerechnet |   |  
Es müssen zwei Tage gewählt werden |   |  
  |   |  
nicht spielfähig in diesem Jahr |   |  
SUISA über Dritte abgerechnet |   |  
Anmeldungen Export |   |  
Um die SUISA-Meldeliste einzureichen müssen Sie mindestens eine Aufführung hinzufügen oder eine alternative Erledigung wählen: |   |  
Musikfest erstellen |   |  
Herzlichen Dank für die Anmeldung. |   |  

Möchtest du dies direkt in dieser Tabelle machen oder soll ich dir, oder dem SBV ein Login auf Transifex.com (unserem Übersetzungstool) geben?

**Comment by betsim** [comment]
Mach mir doch eine Login, dann schaue ich für die Übersetzungen und trage sie dort ein.

**Comment by olibrian** [comment]
Du solltest eine Einladung erhalten habe. Anschliessend kann ich dir noch mehr Rechte für die Übersetzung von allen Sprachen geben.

**Comment by betsim** [comment]
Bin registriert 👍🏻

**Comment by olibrian** [comment]
Gut, jetzt solltest du `fr` und `it` übersetzten dürfen.. (hoffentlich auch können :-)

**Comment by olibrian** [comment]
Melde dich kurz, wenn die Übersetzungen drin sind. Anschliessend müssen wir nochmals ein kleiner Release machen..

**Comment by betsim** [comment]
`fr` ist komplett bis auf einen string "gespielt", dessen Kontext für die korrekte Übersetzung massgebend wäre (habe einen Kommentar auf Transifex hinterlassen). Ich finde diesen string aber nirgends in hitobito... gemäss key müsste er im SUISA-Modul verwendet werden, ich finde ihn aber nicht; kannst du weiterhelfen @olibrian ?

`it` folgt in Kürze

**Comment by olibrian** [comment]
Gute Frage.. Kannst du @kronn  uns weiter helfen?
Aus Transifex:
![image](https://user-images.githubusercontent.com/9592347/95587599-8a56dd80-0a42-11eb-8b4c-5637e79bb239.png)
Key: `activerecord.attributes.concert.reasons._nil `

**Comment by kronn** [comment]
Dieser Key wird derzeit nicht im UI verwendet. Er stellt quasi Fehlen eines "Keine Aufführung"-Grundes dar. 

Hintergrund:
Für die SUISA-Meldung kann man ja einen Grund angeben, warum keine Aufführungen stattgefunden haben. Technisch wird hier genauso eine Aufführung angelegt, jedoch mit einem Grund. Die Gründe "Spielgemeinschaft" etc stellen klar, dass es keine Aufführung ist, bei der gespielt wurde, sondern nur ein Platzhalter. Wenn kein Grund vorhanden ist, wird dieser als `NULL` / `nil` / `_nil` interpretiert. Das letzte ist die Darstellung, mit der nach einer Übersetzung gesucht wird. Wenn man nun eine normale Aufführung nach ihrem Daseinsgrund fragt, ist die Antwort: Es wurde __gespielt__.

Hilft dies als Kontext?

**Comment by betsim** [comment]
Ja, danke Matthias!

Die Übersetzungen sind nun komplett.

**Comment by betsim** [comment]
Wann dürfen wir mit einem Release in der Produktivumgebung rechnen? Die SUISA-Eingabe-"Saison" beginnt bald und wir möchten unnötige Rückfragen bei leeren Feldern verhindern.

**Comment by kronn** [comment]
Die Produktivumgebung ist auf Version 1.22.10 aktualisiert und enthält die Übersetzungen.
