### ISSUE TITLE
Einstellungen > Texte: Speichern nicht möglich

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#77]
Im Modul EINSTELLUNGEN --> TEXTE kann z.B. der Text "Meldeliste: E-Mail Erinnerung" nur auf Deutsch bearbeitet werden. Wechselt man die Sprache auf Französisch oder Italienisch und klickt nach dem Übersetzen auf den Speichern-Button erscheint eine leere weisse Seite.

Betrifft: Produktivumgebung SBV

**Comment by kronn** [comment]
Danke für die Fehlermeldung. Der Fehler ist behoben, die Produktivumgebung wurde aktualisiert
