### ISSUE TITLE
Berechnung Aktivjahre

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#78]
**Rechenbeispiel**
Mitglied: 1979-1986 (SOLL: 8 Jahre)
Mitglied: 1994-2005 (SOLL: 12 Jahre)
Mitglied: 2017-2020 (SOLL: 4 Jahre)

**IST**
Aktivjahre = 22

**SOLL**
Aktivjahre = 24

Begründung: Mit VL-Beschluss vom Dezember 2019 (evtl. hitobito nie kommuniziert?) zählen neu alle angefangenen Jahre und nicht mehr nur die vollendeten Jahre, d.h. die Anzahl Aktivjahre berechnet sich für **jede** Mitglied-Rolle durch `JAHR-ENDE minus JAHR-ANFANG plus 1`

**Comment by olibrian** [comment]
VL Beschluss noch offen über die Umsetzung

**Comment by betsim** [comment]
Die VL hat an ihrer Sitzung vom 14.11.2020 folgende Berechnung der Aktivjahre beschlossen:

* jedes angefangene Jahr zählt (d.h. egal an welchem Datum die Rolle «Mitglied» vergeben wurde, massgebend ist das Jahr)  dies hat bei Unterbrüchen Auswirkungen: siehe oben https://github.com/hitobito/hitobito_sbv/issues/78#issue-718863551)
* das 1. Aktivjahr soll in hitobito am 1. Januar im Jahr nach dem Eintrittsjahr angezeigt werden (Beispiel: Eintritt am 1. April yyyy  hitobito zeigt bis zum 31. Dezember yyyy 0 Aktivjahre an und ab dem 1. Januar yyyy+1 zeigt hitobito 1 Aktivjahr an). Beispiele:
 
![image](https://user-images.githubusercontent.com/1453303/99372995-2d600a00-28c1-11eb-9bb3-fdb826287f4a.png)

grau = Periode, während Mitglied Vereinsmitglied (Rolle «Mitglied») ist/war
grün = dieses Jahr zählt | rosa = Jahr zählt nicht

_Pro Memoria: der Bug https://github.com/hitobito/hitobito_sbv/issues/79#issuecomment-718909706 ist ebenfalls noch offen_
