### ISSUE TITLE
Berechnung Aktivjahre: Benoit Favre + Frédéric Stähli

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#79]
**Verlauf**
Société de musique l'Avenir Avry-Matran / Membres | Mitglied | 01.01.2017
Société de musique l'Avenir Avry-Matran / Membres | Mitglied | 01.01.1979 – 31.12.1986 
Société de musique l'Avenir Avry-Matran / Membres | Mitglied | 01.01.1994 – 31.12.2005

siehe: https://db.windband.ch/de/groups/15297/people/67957/history

**IST**
Aktivjahre aktuell = 15

**SOLL**
Aktivjahre aktuell = 24

Abgesehen von #78 scheint bei dieser Person eine der 3 Rollen nicht in die Berechnung miteingeflossen zu sein.

**Comment by betsim** [comment]
**Verlauf**
COLLOMBEYRIENNE Collombey / Mitglieder | Mitglied (Membres) | 01.01.1964 – 31.10.1970
Fanfare Béroche-Bevaix / Membres | Mitglied | 01.01.1970 – 31.12.1981
L'Espérance Cressier / Membres | Mitglied | 01.01.1981
L'Espérance Cressier / Membres | Mitglied | 01.01.1951 – 31.12.1956
MG Concordia Allschwil / Mitglieder | Mitglied (Membres) | 16.11.1959 – 31.12.1964
Musikverein Wohlen / Mitglieder | Mitglied (Membres) | 01.01.1956 – 31.12.1959

siehe: https://db.windband.ch/de/groups/15562/people/68689/history

**IST**
Aktivjahre aktuell = 65

**SOLL**
Aktivjahre aktuell = 70

**Comment by betsim** [comment]
siehe auch: https://github.com/hitobito/hitobito_sbv/issues/78#issuecomment-728811340

**Comment by kronn** [comment]
Mit den Anpassungen für #78 sind die Jahre immer 1 geringer als hier als SOLL angegeben. Sobald das Jahr gewechselt hat, stimmt es dann mit dem hier überein.

**Comment by betsim** [comment]
Die Jahre stimmen weiterhin nicht. Es geht nicht um +-1 Jahr, sondern es werden vom System offensichtlich ganze Perioden nicht mitgezählt.
