### ISSUE TITLE
Menü SUISA trotz Berechtigung nicht sichtbar

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#82]
**IST**
Die Person Ducommun Carole hat die Rolle "Verantwortlicher SUISA", sieht das entsprechende Menü "SUISA" aber nicht. Dies konnte durch immitieren der Person nachvollzogen werden:

![Bildschirmfoto 2020-11-07 um 14 47 22](https://user-images.githubusercontent.com/1453303/98442923-52f25400-2108-11eb-8b1e-e10eebdd44ca.png)

Nachdem ich die Rolle "Verantwortlicher SUISA" geöffnet und diesen Eintrag neu gespeichert hatte, ist das Menü plötzlich da.

**SOLL**
Die zugewiesenen Rollen müssen alle sauber berücksichtigt werden, ohne dass die Rollen nochmals neu gespeichert werden müssten.

**Comment by kronn** [comment]
Leider kann ich den Fehler nicht nachvollziehen. Ich habe es mit einem Datenbank-Backup vom 04.11. nicht nachstellen können. 
Ausweislich den Logs wurde die Rolle am 07.11. ein weiteres mal vergeben und dann wieder gelöscht. Die aktive Rolle ist jedoch noch diejenige, welche im Januar 2020 vergeben wurde. Die Rollen werden nicht besonders zwischengespeichert und bei jeden Aufruf geprüft.  

Mir ist lediglich aufgefallen, dass die primäre Gruppen die Gruppe "Membres" ist. Das SUISA-Menü ist nur auf der Ebenengruppe verfügbar. Könnte dies eine Erklärung sein?

Wenn das beschriebene Verhalten noch bei einer anderen Person zu beobachten ist, bitte ich um erneute Information.

**Comment by betsim** [comment]
Ich glaube du soeben meinen "Fehler" aufgedeckt mit https://github.com/hitobito/hitobito/issues/1076 das stiftet tatsächlich Verwirrung.
