### ISSUE TITLE
Neuer Musikverband accordeon.ch

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#90]
Accordeon.ch nutzt die Superstruktur vom SBV.

Domain: db.accordeon.ch

- [x] neue Dachverband-Gruppe in hitobito Generalverband anlegen
    - [x] Domain auf Dachverband-Gruppe eintragen
    - [x] Logo für Musikerverband hochladen
- [x] DNS-Eintrag machen, um Domain auf SBV-Hitobito zeigen zu lassen
- [x] OpenShift-Route anlegen, um Domain von SBV-Hitobito verarbeiten zu lassen
- [x] Eintrag in Mailkonfiguration machen, um mail an neue Domain in das richtige Postfach zu schieben [PR](https://gitlab.puzzle.ch/pitc_ansible/ansible-puzzle/-/merge_requests/1933)

Gemäss Dokumentation:
https://github.com/hitobito/hitobito_sbv#weiteren-musikerverband-hinzuf%C3%BCgen

**Comment by olibrian** [comment]
Kunde über DNS Anpassungen informiert.

**Comment by olibrian** [comment]
DNS Anpassungen wurden gemacht:

> Guten Tag Herr Hänni
> 
> Die gewünschten DNS Einträge sind erstellt. Es dauert ein paar Stunden, bis diese weltweit aktiv sind.
> 
> Freundliche E-Grüsse
> Christine Koller
> 
> CHRISTINE KOLLER
> WEBPUBLISHER SIZ
> 
> +41 (0)79 54 999 53
> INFO@HALLOHOMEPAGE.CH
> WWW.HALLOHOMEPAGE.CH
>

**Comment by kronn** [comment]
Der PR wurde von /sys gemerged, damit sind aus meiner Sicht keine Punkte mehr offen.

**Comment by olibrian** [comment]
Danke, funktioniert soweit.
