### ISSUE TITLE
SUISA: Werke 2021 werden auf der Seite 2020 angezeigt

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito_sbv#94]
Wenn man für ein Datum im Jahr 2021 eine Aufführung mit Werken erfasst, wird diese anschliessend in der Übersicht für das Jahr 2020 dargestellt (wenn gleich mit dem erfassten 2021-Datum):

![Bug SUISA](https://user-images.githubusercontent.com/1453303/111749231-c6b02480-8891-11eb-8691-0360273959e3.png)

**Comment by olibrian** [comment]
Die Jahresanzeige in der SUISA-Liste bezieht sich nicht auf das Kalenderjahr, sondern auf das "Jahr" der Meldeperiode. Wir könnten die Beschriftung verbessern, um hier Klarheit zu schaffen.

Wenn die Erwartung ist, dass es Kalenderjahre sind, müssten wir einerseits die Logik zum Auslesen anpassen, aber andererseits auch visuell klarstellen, in welche Meldeperiode eine Aufführung einsortiert wurde. Ich sehe das als nicht trivial an, kann aber auch falsch liegen.

Was wäre hier gewollt?

**Comment by betsim** [comment]
Die Meldeperiode war bisher 1.12. bis 30.11. und ab 2021 neu identisch mit dem Kalenderjahr. Mir war nicht bewusst, dass diese Änderung Auswirkungen auf hitobito haben könnte?

Aber das erklärt das Verhalten m.E. nicht, wenn ich am 19.3.21 eine Aufführung vom 1.3.21 erfasse, so muss diese doch 2021 erscheinen und nicht 2020. Oder stehe ich auf dem Schlauch?

**Comment by olibrian** [comment]
Kann es sein, dass die Meldeliste von 2020 noch nicht abgeschlossen ist?

**Comment by betsim** [comment]
Muss man diese in hitobito irgendwo abschliessen? 😳

**Comment by olibrian** [comment]
Ja, es gibt die Funktion "Meldeliste abschliessen" im Tab Suisa. Anschliessend kannst du eine neue Meldeperiode erstellen. Dies betrifft aber alle Verbände in der Superstruktur. Daher wurde dies nicht automatisiert.

**Comment by betsim** [comment]
Alles klar, danke für die Aufklärung. Das müssen wir im Handbuch dokumentieren.
