### ISSUE TITLE
MIGRATION: Setzen der Korrespondenzsprache von Personen aufgrund des zugehörigen Layer

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sbv#99]
Der SBV hat letztes Jahr bei allen Vereinen die Sprache auf dem Layer durchgehend erfasst. Könntet Ihr nun ausgehend von der Spracheinstellung beim Verein, die Sprache bei den Personen einsetzt, wo eine solche fehlt? Sprich wenn beim Verein als Sprache "französisch" erfasst ist, erhalten alle Mitglieder dieses Vereins auch die Spracheinstellung "französisch", sofern sie nichts selber gewählt haben. Und könntet ihr die Sprache auf der Person als Pflichtfeld bei der Erfassung definieren?

**Weiter zu beachten:**
- Sprachauswahl beim Neuerfassen von einer Person als Feld aufnehmen. 
- Registrierung als Externer User für Event

**Offene Fragen:**
- Fallback verhalten von der Migration? Was wenn keine Sprache definiert wurde? -> keine Sprache setzten
- Falls eine Person mehrere Rollen hat, wird die Sprache vom primären Verein, verwendet.
- Was passiert, wenn die Sprache vom Layer geändert wird? Soll die Sprache auf dem Layer readonly werden?
- Soll bei erfassen einer neuen Person das Feld Sprache ein Preselect vom Layer haben?
- Soll auch die Sprache der Layer ein Pflichtfeld sein?

**Tech spec**
- In UI Feld / Model jeweils auf required setzen, aber in DB noch nullable

**Comment by betsim** [comment]
> **Offene Fragen:**
> 
> * Fallback verhalten von der Migration? Was wenn keine Sprache definiert wurde? -> keine Sprache setzten

Ja

> * Falls eine Person mehrere Rollen hat, wird die Sprache vom primären Verein, verwendet.

Ja

> * Was passiert, wenn die Sprache vom Layer geändert wird? Soll die Sprache auf dem Layer readonly werden?

Die Sprache soll einmalig gesetzt werden. Zukünftige Änderungen am Layer müssen nicht "nachgeführt" werden. Es soll keine Verknüpfung der Sprachfelder entstehen, sondern nur eine einmalige "Migration".

> * Soll bei erfassen einer neuen Person das Feld Sprache ein Preselect vom Layer haben?

Ja

> * Soll auch die Sprache der Layer ein Pflichtfeld sein?

Das ist nicht nötig, weil dies eine einmalige Sache ist.

**Comment by chrusu** [comment]
@TheWalkingLeek @luca-bruegger @kronn @carlobeltrame Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito_sbv/99?planning-poker)

**Comment by olibrian** [comment]
Einige Korrespondenzsprachen wurden wohl noch nicht gesetzt. Beispiel: https://db.windband.ch/de/groups/1582/people?returning=true Da ist die Korrespondenzsprache nicht bei allen Personen gesetzt. Ich habe auch noch weitere Vereine gesehen, bei denen es nicht geklappt hat.

**Comment by betsim** [comment]
**IST**
Bei der Anmeldung einer externen Person für einen Kurs fehlt das Feld "Korrespondenzsprache" im Anmeldeformular, aber das Feld wird als Pflichtfeld validiert (z.B. https://db.windband.ch/de/groups/33218/events/803/register). Entsprechend ist zur Zeit die Anmeldung von externen Personen für Kurse nicht möglich.

**SOLL**
Auch bei der Registrierung externer Personen ist das Feld "Korrespondenzsprache" als Pflichtfeld vorhanden und zu validieren. Bitte deshalb das entsprechende Feld im Anmeldeformular ergänzen.
